### ISSUE TITLE
Image operations change the original image

### ISSUE THREAD

**Issue by peeter-tomberg** [EyalAr/lwip#111]
```javascript
var lwip = require('lwip');

lwip.open(__dirname + '/250x200.gif', function (err, image) {
    console.log('Original image size:', image.width(), image.height());
    image.resize(100, 100, function (err, newImage) {
        console.log('After operation', image.width(), image.height());
    });
});
```

The following example prints out 
```
Original image size: 250 200
After cover function: 100 100
```

If this is intended behavior, then I find the entire API a bit confusing. Why am I being passed a new instance of the image for every non-batched image operation when the original one has been tampered with?

**Comment by EyalAr** [comment]
It is the intended behavior.
You are not being passed a new instance. It's exactly the same instance.
You can check with your example, by verifying `image === newImage`.
It's just for convenience, as, indeed, the original image is modified.

Should note that if you choose to use `image` from the outer scope in the resize callback, instead of using a local `image` reference, a closure is created to keep the outer scope in memory.
