### ISSUE TITLE
batch.setPixel slow?

### ISSUE THREAD

**Issue by trsh** [EyalAr/lwip#210]
These lines (see below) take up to 14 sec on node. Where similar code HTML5 canvas (just pure JS), take one 1 sec (or less). Why?

lwip.create(800, 600, function(err, image) {
                if (err) return console.log(err);

                var x, y, c, batch = image.batch();

                for (x = 0; x < 800 ; x++){

                    for (y = 0; y < 600; y++){

                        /*var r = Math.random() * 256 | 0;
                        var g = Math.random() * 256 | 0;
                        var b = Math.random() * 256 | 0;*/

                        c = {r: 1, g: 12, b: 100, a: 100};

                        batch.setPixel(x, y, c);
                    }
                }

                batch.writeFile(process.env.PWD+'/public/exports/new_image.png', function(err){
                    if (err) console.log(err);
                });
            });

**Comment by rasteiner** [comment]
getPixel and setPixel are "slow" when iterated upon, I guess that's because there's an overhead for moving data between JS and the bound binaries. 

If you create the whole image in JS and move the whole thing to lwip it will be much faster. 
lwip accepts a "raw pixel buffer" when opening images, so you could do:

```javascript
var lwip = require('lwip');

var w = 800,
    h = 600;

var x,y;
var buffer = new Buffer(w * h * 4);

//the buffer will contain:
//    w * h integers of Red, then
//    w * h integers of Green, then
//    w * h integers of Blue and finally
//    w * h integers of Alpha
function setPixel(x,y,c) {
    buffer[x+y*w]           = c.r;
    buffer[(w*h)+(x+y*w)]   = c.g;
    buffer[(2*w*h)+(x+y*w)] = c.b;
    buffer[(3*w*h)+(x+y*w)] = c.a;
}

for (x = 0; x < 800 ; x++){
    for (y = 0; y < 600; y++){
        c = {r: 1, g: 12, b: 100, a: 100};
        setPixel(x, y, c);
    }
}

var img = lwip.open(buffer, {width: w, height: h}, function(err, img) {
    img.writeFile(process.env.PWD+'/public/exports/new_image.png', function(err){
        if (err) console.log(err);
    });
});
```

This executes in less than a second here. 

So, try to avoid to iterate over getPixel and setPixel. Work directly on the buffer. 

PS: if you want to iterate over "getPixel", you get access to the raw pixel buffer through an undocumented, synchronous, function doing `var buffer = img.__lwip.buffer();`. 

IMO it could be useful to expose the "hidden" `.__lwip.buffer()` function to javascript through the offical API, maybe having something like `img.toBuffer('pixelmap', function(err, buffer){...})`. The performance benefits are significant (at least speedwise), like demoed here: https://github.com/rasteiner/lwip-test.

**Comment by trsh** [comment]
Thanks!
